#!/usr/bin/env python3
"""Generate pros_cons_generator.py"""
import os

lines = []
lines.append('"""')
lines.append('pros_cons_generator.py')
lines.append('')
lines.append('NLP Auto Pros/Cons Generator - Sprint 5 Module 2.')
lines.append('')
lines.append('Automatically generates financial Pros and Cons for all companies')
lines.append('using deterministic financial rules from the SQLite database.')
lines.append('')
lines.append('Output: output/pros_cons_generated.csv')
lines.append('Required columns: company_id, type, rule_id, text, confidence_pct')
lines.append('Only confidence_pct > 60 included.')
lines.append('"""')
lines.append('')
lines.append('from __future__ import annotations')
lines.append('')
lines.append('import logging')
lines.append('import os')
lines.append('import sqlite3')
lines.append('import time')
lines.append('from datetime import datetime')
lines.append('from pathlib import Path')
lines.append('from typing import Any, Dict, List, Optional, Tuple')
lines.append('')
lines.append('import numpy as np')
lines.append('import pandas as pd')
lines.append('')
lines.append('from src.config.constants import DATABASE_DIR, OUTPUT_DIR')
lines.append('from src.config.logging_config import get_logger')
lines.append('')
lines.append('logger = get_logger(__name__)')
lines.append('')
lines.append('# =============================================================================')
lines.append('# CONSTANTS')
lines.append('# =============================================================================')
lines.append('')
lines.append('DEFAULT_DB_PATH: Path = DATABASE_DIR / "n100.db"')
lines.append('PROS_CONS_CSV_PATH: Path = OUTPUT_DIR / "pros_cons_generated.csv"')
lines.append('')
lines.append('CONFIDENCE_MIN: float = 61.0')
lines.append('CONFIDENCE_MAX: float = 95.0')
lines.append('CONFIDENCE_BASE: float = 65.0')
lines.append('CONFIDENCE_DISTANCE_FACTOR: float = 30.0')
lines.append('')
lines.append('PRO_01_ROE_THRESHOLD: float = 20.0')
lines.append('PRO_04_REVENUE_CAGR_THRESHOLD: float = 15.0')
lines.append('PRO_05_OPM_THRESHOLD: float = 25.0')
lines.append('PRO_06_PAT_CAGR_THRESHOLD: float = 20.0')
lines.append('PRO_07_ICR_THRESHOLD: float = 10.0')
lines.append('PRO_08_DIV_YIELD_THRESHOLD: float = 2.0')
lines.append('PRO_09_EPS_CAGR_THRESHOLD: float = 15.0')
lines.append('CON_01_DE_THRESHOLD: float = 2.0')
lines.append('CON_06_ICR_THRESHOLD: float = 1.5')
lines.append('CON_10_ROCE_THRESHOLD: float = 10.0')
lines.append('CON_11_NET_DEBT_EBITDA_RATIO: float = 3.0')
lines.append('CON_12_REVENUE_CAGR_THRESHOLD: float = 5.0')
lines.append('')
lines.append('PRO_01_ROE_YEARS: int = 3')
lines.append('PRO_02_FCF_YEARS: int = 5')
lines.append('PRO_10_ROE_IMPROVE_YEARS: int = 3')
lines.append('CON_02_FCF_YEARS: int = 3')
lines.append('CON_03_OPM_DECLINE_YEARS: int = 3')
lines.append('CON_05_REVENUE_DECLINE_YEARS: int = 2')
lines.append('CON_08_DE_RISE_YEARS: int = 3')
lines.append('CON_09_EPS_DECLINE_YEARS: int = 3')
lines.append('')
lines.append('FINANCIAL_SUB_SECTORS: frozenset = frozenset({')
lines.append('    "Private Banks",')
lines.append('    "Public Sector Banks",')
lines.append('    "Life Insurance",')
lines.append('    "General Insurance",')
lines.append('    "Diversified Financials",')
lines.append('    "Speciality Finance",')
lines.append('})')

with open('src/nlp/pros_cons_generator.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
    f.write('\n')
print('Part 1 written')

#!/usr/bin/env python3
