import sqlite3
conn = sqlite3.connect('data/database/n100.db')
conn.row_factory = sqlite3.Row
print('=== companies cols ===')
print([d[0] for d in conn.execute('PRAGMA table_info(companies)').fetchall()])
r = conn.execute('SELECT * FROM companies LIMIT 1').fetchone()
print('sample:', dict(r))
print('=== sectors table ===')
print([d[0] for d in conn.execute('PRAGMA table_info(sectors)').fetchall()])
rows = conn.execute('SELECT DISTINCT broad_sector FROM sectors WHERE broad_sector IS NOT NULL').fetchall()
print('distinct broad_sector:', [r[0] for r in rows])
print('sectors rows:', conn.execute('SELECT COUNT(*) FROM sectors').fetchone()[0])
print('companies without sector entry:', conn.execute('SELECT COUNT(*) FROM companies WHERE company_id NOT IN (SELECT company_id FROM sectors)').fetchone()[0])
print('=== financial_kpis cols ===')
print([d[0] for d in conn.execute('PRAGMA table_info(financial_kpis)').fetchall()])
print('latest period count (Mar 2024):', conn.execute("SELECT COUNT(*) FROM financial_kpis WHERE period='Mar 2024'").fetchone()[0])
r = conn.execute("SELECT * FROM financial_kpis WHERE company_id='ABB' ORDER BY period DESC LIMIT 1").fetchone()
print('ABB sample:', dict(r))
print('=== peer_percentiles ===')
print([d[0] for d in conn.execute('PRAGMA table_info(peer_percentiles)').fetchall()])
r = conn.execute('SELECT * FROM peer_percentiles LIMIT 1').fetchone()
print('sample:', dict(r))
print('distinct peer_group_name in peer_percentiles:', [r[0] for r in conn.execute('SELECT DISTINCT peer_group_name FROM peer_percentiles').fetchall()])
print('distinct metric in peer_percentiles:', [r[0] for r in conn.execute('SELECT DISTINCT metric FROM peer_percentiles').fetchall()])
print('distinct period in peer_percentiles:', [r[0] for r in conn.execute('SELECT DISTINCT period FROM peer_percentiles').fetchall()])
print('=== market_cap cols & sample ===')
print([d[0] for d in conn.execute('PRAGMA table_info(market_cap)').fetchall()])
r = conn.execute("SELECT * FROM market_cap WHERE company_id='ABB'").fetchone()
print('ABB market_cap:', dict(r) if r else None)
print('=== companies sample tickers ===')
for r in conn.execute('SELECT company_id, company_name FROM companies LIMIT 8'): print(r[0], '|', r[1])
print('=== peer_groups distinct + counts ===')
for r in conn.execute('SELECT peer_group_name, COUNT(*), SUM(is_benchmark) FROM peer_groups GROUP BY peer_group_name ORDER BY peer_group_name'):
    print(r[0], 'count=', r[1], 'benchmark=', r[2])
conn.close()
