#!/usr/bin/env python3
import os

TARGET = "src/nlp/pros_cons_generator.py"

# We build the file content line by line
content = []

def L(text=""):
    content.append(text)

L('"""')
L('pros_cons_generator.py')
L('')
L('NLP Auto Pros/Cons Generator for the N100 Financial Intelligence Platform.')
L('')
L('Sprint 5 - Module 2')
L('')
L('Automatically generates financial Pros and Cons for all companies using')
L('deterministic financial rules derived from the SQLite database.')
L('')
L('Output:')
L('    output/pros_cons_generated.csv')
L('')
L('Required columns:')
L('    company_id, type, rule_id, text, confidence_pct')
L('')
L('Only rules with confidence_pct > 60 are included.')
L('"""')
L('')
L('from __future__ import annotations')
L('')
L('import logging')
L('import os')
L('import sqlite3')
L('import time')
L('from datetime import datetime')
L('from pathlib import Path')
L('from typing import Any, Dict, List, Optional, Tuple')
L('')
L('import numpy as np')
L('import pandas as pd')
L('')
L('from src.config.constants import DATABASE_DIR, OUTPUT_DIR')
L('from src.config.logging_config import get_logger')
L('')
L('logger = get_logger(__name__)')
L('')

#!/usr/bin/env python3
CHUNKS = []

def add(text):
    CHUNKS.append(text)



L('# =============================================================================')
L('# DATA LOADING')
L('# =============================================================================')
L('')
L('')
L('def load_company_data(company_id: str, conn: sqlite3.Connection) -> Dict[str, Any]:')
L('    """')
L('    Load all required financial data for a single company.')
L('')
L('    Returns dict with keys:')
L('        company_id, sector, sub_sector, is_financial,')
L('        annual_kpis (list, newest->oldest),')
L('        annual_pl   (list, newest->oldest),')
L('        annual_bs   (list, newest->oldest, deduplicated by year),')
L('        ttm_kpis    (dict or None),')
L('        cash_flow   (list, newest->oldest)')
L('    """')
L('    data: Dict[str, Any] = {')
L('        "company_id": company_id,')
L('        "sector": None,')
L('        "sub_sector": None,')
L('        "is_financial": False,')
L('        "annual_kpis": [],')
L('        "annual_pl": [],')
L('        "annual_bs": [],')
L('        "ttm_kpis": None,')
L('        "cash_flow": [],')
L('    }')
L('')
L('    sub_sector = get_company_sector(company_id, conn)')
L('    data["sub_sector"] = sub_sector')
L('    data["is_financial"] = (')
L('        sub_sector in FINANCIAL_SUB_SECTORS if sub_sector else False')
L('    )')
L('')
L('    # financial_kpis annual rows')
L('    try:')
L('        cursor = conn.execute(')
L('            """')
L('            SELECT period, roe, roce, operating_margin,')
L('                   debt_to_equity, interest_coverage, free_cash_flow,')
L('                   dividend_yield, revenue_cagr, profit_cagr, eps_cagr')
L('            FROM financial_kpis')
L('            WHERE company_id = ? AND period != "TTM"')
L('            ORDER BY period DESC')
L('            """,')
L('            (company_id,),')
L('        )')
L('        data["annual_kpis"] = [dict(row) for row in cursor.fetchall()]')
L('    except Exception as exc:')
L('        logger.warning("Failed to load financial_kpis for %s: %s", company_id, exc)')
L('')
L('    # TTM row')
L('    try:')
L('        cursor = conn.execute(')
L('            """')
L('            SELECT period, roe, roce, operating_margin,')
L('                   debt_to_equity, interest_coverage, free_cash_flow,')
L('                   dividend_yield, revenue_cagr, profit_cagr, eps_cagr')
L('            FROM financial_kpis')
L('            WHERE company_id = ? AND period = "TTM"')
L('            LIMIT 1')
L('            """,')
L('            (company_id,),')
L('        )')
L('        row = cursor.fetchone()')
L('        data["ttm_kpis"] = dict(row) if row else None')
L('    except Exception as exc:')
L('        logger.warning("Failed to load TTM KPIs for %s: %s", company_id, exc)')
L('')
L('    # profit_loss')
L('    try:')
L('        cursor = conn.execute(')
L('            """')
L('            SELECT period, sales, operating_profit, opm_percentage,')
L('                   other_income, interest, depreciation,')
L('                   net_profit, eps, dividend_payout')
L('            FROM profit_loss')
L('            WHERE company_id = ?')
L('            ORDER BY period DESC')
L('            """,')
L('            (company_id,),')
L('        )')
L('        data["annual_pl"] = [dict(row) for row in cursor.fetchall()]')
L('    except Exception as exc:')
L('        logger.warning("Failed to load profit_loss for %s: %s", company_id, exc)')
L('')
L('    # balance_sheet (annual only)')
L('    try:')
L('        cursor = conn.execute(')
L('            """')
L('            SELECT period, borrowings, investments, total_assets,')
L('                   equity_capital, reserves')
L('            FROM balance_sheet')
L('            WHERE company_id = ?')
L('              AND period NOT LIKE "Sep%"')
L('              AND period NOT LIKE "Jun%"')
L('              AND period NOT LIKE "Dec%"')
L('            ORDER BY period DESC')
L('            """,')
L('            (company_id,),')
L('        )')
L('        data["annual_bs"] = [dict(row) for row in cursor.fetchall()]')
L('    except Exception as exc:')
L('        logger.warning("Failed to load balance_sheet for %s: %s", company_id, exc)')
L('')
L('    # cash_flow')
L('    try:')
L('        cursor = conn.execute(')
L('            """')
L('            SELECT period, cash_from_operating_activity,')
L('                   cash_from_investing_activity, cash_from_financing_activity,')
L('                   free_cash_flow')
L('            FROM cash_flow')
L('            WHERE company_id = ?')
L('            ORDER BY period DESC')
L('            """,')
L('            (company_id,),')
L('        )')
L('        data["cash_flow"] = [dict(row) for row in cursor.fetchall()]')
L('    except Exception as exc:')
L('        logger.warning("Failed to load cash_flow for %s: %s", company_id, exc)')
L('')
L('    return data')

L('# =============================================================================')
L('# PERIOD HELPERS')
L('# =============================================================================')
L('')
L('')
L('def _parse_period_year(period: Optional[str]) -> Optional[int]:')
L('    """Extract year integer from period string."""')
L('    if not period:')
L('        return None')
L('    period = str(period).strip()')
L('    for part in period.split():')
L('        if part.isdigit() and len(part) == 4:')
L('            return int(part)')
L('    if "-" in period:')
L('        for part in period.split("-"):')
L('            part = part.strip()')
L('            if part.isdigit():')
L('                year = int(part)')
L('                return 2000 + year if year < 100 else year')
L('    return None')
L('')
L('')
L('def _deduplicate_annual(records: List[Dict[str, Any]]) -> List[Dict[str, Any]]:')
L('    """Keep only the latest entry per year."""')
L('    year_map: Dict[int, Dict[str, Any]] = {}')
L('    for rec in records:')
L('        year = _parse_period_year(rec.get("period"))')
L('        if year is None:')
L('            continue')
L('        if year not in year_map:')
L('            year_map[year] = rec')
L('    result = sorted(')
L('        year_map.values(),')
L('        key=lambda r: _parse_period_year(r.get("period")) or 0,')
L('        reverse=True,')
L('    )')
L('    return result')
L('')
L('')
L('# =============================================================================')
L('# VALUE HELPERS')
L('# =============================================================================')
L('')
L('')
L('def _safe_float(value: Any) -> Optional[float]:')
L('    """Safely convert value to float, returning None for invalid input."""')
L('    if value is None:')
L('        return None')
L('    try:')
L('        v = float(value)')
L('        return v if not (np.isnan(v) or np.isinf(v)) else None')
L('    except (TypeError, ValueError):')
L('        return None')
L('')
L('')
L('def _get_numeric(records: List[Dict[str, Any]], key: str, index: int = 0) -> Optional[float]:')
L('    """Get a numeric value from records at a given index (0 = newest)."""')
L('    if index < 0 or index >= len(records):')
L('        return None')
L('    return _safe_float(records[index].get(key))')
L('')
L('')
L('def _extract_annual_trend(')
L('    records: List[Dict[str, Any]], key: str, n_years: int')
L(') -> List[Optional[float]]:')
L('    """Extract up to n_years numeric values (newest -> oldest)."""')
L('    values = []')
L('    for i in range(min(n_years, len(records))):')
L('        values.append(_safe_float(records[i].get(key)))')
L('    return values')
L('')
L('')
L('# =============================================================================')
L('# CONFIDENCE SCORING')
L('# =============================================================================')
L('')
L('')
L('def calculate_confidence(')
L('    value: Optional[float],')
L('    threshold: float,')
L('    *,')
L('    higher_is_better: bool = True,')
L('    distance_factor: float = CONFIDENCE_DISTANCE_FACTOR,')
L(') -> Optional[float]:')
L('    """')
L('    Compute deterministic confidence score for a threshold-based rule.')
L('    confidence = clamp(65 + raw_distance * 30, 61, 95)')
L('    """')
L('    if value is None:')
L('        return None')
L('    raw_distance = (value - threshold) / max(abs(threshold), 1e-9)')
L('    if not higher_is_better:')
L('        raw_distance = -raw_distance')
L('    confidence = CONFIDENCE_BASE + raw_distance * distance_factor')
L('    confidence = max(CONFIDENCE_MIN, min(CONFIDENCE_MAX, confidence))')
L('    return round(confidence, 2)')
L('')
L('')
L('def calculate_trend_confidence(')
L('    values: List[Optional[float]],')
L('    *,')
L('    improving: bool = True,')
L(') -> Optional[float]:')
L('    """Compute confidence for a trend rule using average YoY relative change."""')
L('    valid = [v for v in values if v is not None]')
L('    if len(valid) < 2:')
L('        return None')
L('    changes = []')
L('    for i in range(len(valid) - 1):')
L('        older = valid[i + 1]')
L('        newer = valid[i]')
L('        if older == 0:')
L('            continue')
L('        rel_change = (newer - older) / max(abs(older), 1e-9)')
L('        changes.append(rel_change)')
L('    if not changes:')
L('        return CONFIDENCE_BASE')
L('    avg_change = sum(changes) / len(changes)')
L('    if not improving:')
L('        avg_change = -avg_change')
L('    if avg_change <= 0:')
L('        return CONFIDENCE_BASE')
L('    confidence = CONFIDENCE_BASE + avg_change * CONFIDENCE_DISTANCE_FACTOR')
L('    confidence = max(CONFIDENCE_MIN, min(CONFIDENCE_MAX, confidence))')
L('    return round(confidence, 2)')
L('')


L('# =============================================================================')
L('# PRO RULES (1-6)')
L('# =============================================================================')
L('')
L('')
L('def _pro_01_roe_sustained(data):')
L('    """PRO_01: ROE > 20% sustained for 3+ consecutive years."""')
L('    roe_values = _extract_annual_trend(data["annual_kpis"], "roe", PRO_01_ROE_YEARS)')
L('    valid = [v for v in roe_values if v is not None]')
L('    if len(valid) < PRO_01_ROE_YEARS:')
L('        return None')
L('    if all(v > PRO_01_ROE_THRESHOLD for v in valid):')
L('        confidence = calculate_confidence(valid[0], PRO_01_ROE_THRESHOLD, higher_is_better=True)')
L('        return {"rule_id": "PRO_01", "text": "Consistently high return on equity above 20% demonstrates exceptional capital efficiency", "confidence_pct": confidence}')
L('    return None')
L('')
L('')
L('def _pro_02_fcf_positive_5yr(data):')
L('    """PRO_02: FCF positive for 5+ consecutive years."""')
L('    fcf_values = _extract_annual_trend(data["annual_kpis"], "free_cash_flow", PRO_02_FCF_YEARS)')
L('    valid_fcf = [v for v in fcf_values if v is not None]')
L('    if len(valid_fcf) < PRO_02_FCF_YEARS:')
L('        cf_values = _extract_annual_trend(data["cash_flow"], "free_cash_flow", PRO_02_FCF_YEARS)')
L('        valid_fcf = [v for v in cf_values if v is not None]')
L('    if len(valid_fcf) < PRO_02_FCF_YEARS:')
L('        return None')
L('    if all(v > 0 for v in valid_fcf):')
L('        confidence = calculate_confidence(valid_fcf[0], 0, higher_is_better=True)')
L('        return {"rule_id": "PRO_02", "text": "Strong free cash flow generation over 5 years signals healthy business fundamentals", "confidence_pct": confidence}')
L('    return None')
L('')
L('')
L('def _pro_03_debt_free(data):')
L('    """PRO_03: Latest-year D/E = 0 (debt-free)."""')
L('    de = _get_numeric(data["annual_kpis"], "debt_to_equity", 0)')
L('    if de is None:')
L('        bs = _deduplicate_annual(data["annual_bs"])')
L('        if bs:')
L('            borrowings = _safe_float(bs[0].get("borrowings"))')
L('            if borrowings is not None and borrowings == 0:')
L('                de = 0.0')
L('    if de is not None and de == 0.0:')
L('        return {"rule_id": "PRO_03", "text": "Debt-free balance sheet provides financial flexibility and eliminates interest burden", "confidence_pct": CONFIDENCE_MAX}')
L('    return None')
L('')
L('')
L('def _pro_04_revenue_cagr_5yr(data):')
L('    """PRO_04: Revenue CAGR > 15% over 5 years (from TTM row)."""')
L('    ttm = data.get("ttm_kpis")')
L('    if not ttm:')
L('        return None')
L('    cagr = _safe_float(ttm.get("revenue_cagr"))')
L('    if cagr is None:')
L('        return None')
L('    if cagr > PRO_04_REVENUE_CAGR_THRESHOLD:')
L('        confidence = calculate_confidence(cagr, PRO_04_REVENUE_CAGR_THRESHOLD, higher_is_better=True)')
L('        return {"rule_id": "PRO_04", "text": "Revenue growing at above 15% CAGR over 5 years reflects strong business momentum", "confidence_pct": confidence}')
L('    return None')
L('')
L('')
L('def _pro_05_opm_latest(data):')
L('    """PRO_05: Latest-year OPM > 25%."""')
L('    opm = _get_numeric(data["annual_kpis"], "operating_margin", 0)')
L('    if opm is None:')
L('        opm = _get_numeric(data["annual_pl"], "opm_percentage", 0)')
L('    if opm is not None and opm > PRO_05_OPM_THRESHOLD:')
L('        confidence = calculate_confidence(opm, PRO_05_OPM_THRESHOLD, higher_is_better=True)')
L('        return {"rule_id": "PRO_05", "text": "Operating profit margin above 25% indicates strong pricing power and cost discipline", "confidence_pct": confidence}')
L('    return None')
L('')
L('')
L('def _pro_06_pat_cagr_5yr(data):')
L('    """PRO_06: PAT CAGR > 20% over 5 years (from TTM row)."""')
L('    ttm = data.get("ttm_kpis")')
L('    if not ttm:')
L('        return None')
L('    cagr = _safe_float(ttm.get("profit_cagr"))')
L('    if cagr is None:')
L('        return None')
L('    if cagr > PRO_06_PAT_CAGR_THRESHOLD:')
L('        confidence = calculate_confidence(cagr, PRO_06_PAT_CAGR_THRESHOLD, higher_is_better=True)')
L('        return {"rule_id": "PRO_06", "text": "Net profit compounding at above 20% over 5 years creates significant shareholder value", "confidence_pct": confidence}')
L('    return None')
L('')
L('')
L('def _pro_07_icr_high_or_debt_free(data):')
L('    """PRO_07: ICR > 10 OR Debt Free."""')
L('    de = _get_numeric(data["annual_kpis"], "debt_to_equity", 0)')
L('    if de is None:')
L('        bs = _deduplicate_annual(data["annual_bs"])')
L('        if bs:')
L('            borrowings = _safe_float(bs[0].get("borrowings"))')
L('            if borrowings is not None and borrowings == 0:')
L('                de = 0.0')
L('    if de is not None and de == 0.0:')
L('        return {"rule_id": "PRO_07", "text": "Very high interest coverage ratio reflects negligible financial stress from debt servicing", "confidence_pct": CONFIDENCE_MAX}')
L('    icr = _get_numeric(data["annual_kpis"], "interest_coverage", 0)')
L('    if icr is not None and icr > PRO_07_ICR_THRESHOLD:')
L('        confidence = calculate_confidence(icr, PRO_07_ICR_THRESHOLD, higher_is_better=True)')
L('        return {"rule_id": "PRO_07", "text": "Very high interest coverage ratio reflects negligible financial stress from debt servicing", "confidence_pct": confidence}')
L('    return None')
L('')


L('def _pro_08_dividend_yield_fcf(data):')
L('    """PRO_08: Dividend Yield > 2% AND FCF positive."""')
L('    ttm = data.get("ttm_kpis")')
L('    if not ttm:')
L('        return None')
L('    div_yield = _safe_float(ttm.get("dividend_yield"))')
L('    if div_yield is None or div_yield <= PRO_08_DIV_YIELD_THRESHOLD:')
L('        return None')
L('    fcf_values = _extract_annual_trend(data["annual_kpis"], "free_cash_flow", 1)')
L('    valid_fcf = [v for v in fcf_values if v is not None]')
L('    if not valid_fcf:')
L('        cf_values = _extract_annual_trend(data["cash_flow"], "free_cash_flow", 1)')
L('        valid_fcf = [v for v in cf_values if v is not None]')
L('    if not valid_fcf or valid_fcf[0] <= 0:')
L('        return None')
L('    confidence = calculate_confidence(div_yield, PRO_08_DIV_YIELD_THRESHOLD, higher_is_better=True)')
L('    return {"rule_id": "PRO_08", "text": "Consistent dividend yield above 2% backed by positive free cash flow", "confidence_pct": confidence}')
L('')
L('')
L('def _pro_09_eps_cagr_5yr(data):')
L('    """PRO_09: EPS CAGR > 15% over 5 years (from TTM row)."""')
L('    ttm = data.get("ttm_kpis")')
L('    if not ttm:')
L('        return None')
L('    cagr = _safe_float(ttm.get("eps_cagr"))')
L('    if cagr is None:')
L('        return None')
L('    if cagr > PRO_09_EPS_CAGR_THRESHOLD:')
L('        confidence = calculate_confidence(cagr, PRO_09_EPS_CAGR_THRESHOLD, higher_is_better=True)')
L('        return {"rule_id": "PRO_09", "text": "Earnings per share growing above 15% CAGR indicates strong earnings quality and compounding", "confidence_pct": confidence}')
L('    return None')
L('')
L('')
L('def _pro_10_roe_improving_3yr(data):')
L('    """PRO_10: ROE improving for 3 consecutive years."""')
L('    roe_values = _extract_annual_trend(data["annual_kpis"], "roe", PRO_10_ROE_IMPROVE_YEARS)')
L('    valid = [v for v in roe_values if v is not None]')
L('    if len(valid) < PRO_10_ROE_IMPROVE_YEARS:')
L('        return None')
L('    improving = all(valid[i] > valid[i + 1] for i in range(len(valid) - 1))')
L('    if improving:')
L('        confidence = calculate_trend_confidence(valid, improving=True)')
L('        return {"rule_id": "PRO_10", "text": "Return on equity improving for 3 consecutive years shows strengthening business quality", "confidence_pct": confidence}')
L('    return None')
L('')
L('')
L('def _pro_11_revenue_cagr_gt_pat_cagr(data):')
L('    """PRO_11: Revenue CAGR > PAT CAGR. NOTE: Condition implemented as stated; text may contradict condition."""')
L('    ttm = data.get("ttm_kpis")')
L('    if not ttm:')
L('        return None')
L('    rev_cagr = _safe_float(ttm.get("revenue_cagr"))')
L('    pat_cagr = _safe_float(ttm.get("profit_cagr"))')
L('    if rev_cagr is None or pat_cagr is None:')
L('        return None')
L('    if rev_cagr > pat_cagr:')
L('        diff = rev_cagr - pat_cagr')
L('        raw_distance = diff / max(abs(pat_cagr), 1e-9)')
L('        confidence = CONFIDENCE_BASE + raw_distance * CONFIDENCE_DISTANCE_FACTOR')
L('        confidence = max(CONFIDENCE_MIN, min(CONFIDENCE_MAX, confidence))')
L('        confidence = round(confidence, 2)')
L('        return {"rule_id": "PRO_11", "text": "Revenue growing slower than profits shows improving operating leverage and scale benefits", "confidence_pct": confidence}')
L('    return None')
L('')
L('')
L('def _pro_12_assets_growing_debt_declining(data):')
L('    """PRO_12: Balance sheet assets growing with declining debt."""')
L('    bs = _deduplicate_annual(data["annual_bs"])')
L('    if len(bs) < 2:')
L('        return None')
L('    assets = [_safe_float(bs[i].get("total_assets")) for i in range(2)]')
L('    borrowings = [_safe_float(bs[i].get("borrowings")) for i in range(2)]')
L('    if any(v is None for v in assets + borrowings):')
L('        return None')
L('    if assets[0] > assets[1] and borrowings[0] < borrowings[1]:')
L('        asset_change = (assets[0] - assets[1]) / max(abs(assets[1]), 1e-9)')
L('        debt_change = (borrowings[1] - borrowings[0]) / max(abs(borrowings[1]), 1e-9)')
L('        raw_distance = (asset_change + debt_change) / 2')
L('        confidence = CONFIDENCE_BASE + raw_distance * CONFIDENCE_DISTANCE_FACTOR')
L('        confidence = max(CONFIDENCE_MIN, min(CONFIDENCE_MAX, confidence))')
L('        confidence = round(confidence, 2)')
L('        return {"rule_id": "PRO_12", "text": "Growing asset base funded by internal accruals reflects self-sustaining growth", "confidence_pct": confidence}')
L('    return None')
L('')
L('')
L('PRO_RULE_FUNCTIONS = [')
L('    _pro_01_roe_sustained,')
L('    _pro_02_fcf_positive_5yr,')
L('    _pro_03_debt_free,')
L('    _pro_04_revenue_cagr_5yr,')
L('    _pro_05_opm_latest,')
L('    _pro_06_pat_cagr_5yr,')
L('    _pro_07_icr_high_or_debt_free,')
L('    _pro_08_dividend_yield_fcf,')
L('    _pro_09_eps_cagr_5yr,')
L('    _pro_10_roe_improving_3yr,')
L('    _pro_11_revenue_cagr_gt_pat_cagr,')
L('    _pro_12_assets_growing_debt_declining,')
L(']')
L('')


L('# =============================================================================')
L('# CON RULES (1-6)')
L('# =============================================================================')
L('')
L('')
L('def _con_01_de_high_non_financial(data, conn):')
L('    """CON_01: D/E > 2.0 AND NOT Financials."""')
L('    if data.get("is_financial", False):')
L('        return None')
L('    de = _get_numeric(data["annual_kpis"], "debt_to_equity", 0)')
L('    if de is None:')
L('        bs = _deduplicate_annual(data["annual_bs"])')
L('        if bs:')
L('            borrowings = _safe_float(bs[0].get("borrowings"))')
L('            equity = _safe_float(bs[0].get("equity_capital")) or 0')
L('            reserves = _safe_float(bs[0].get("reserves")) or 0')
L('            total_equity = equity + reserves')
L('            if total_equity > 0 and borrowings is not None:')
L('                de = borrowings / total_equity')
L('    if de is not None and de > CON_01_DE_THRESHOLD:')
L('        confidence = calculate_confidence(de, CON_01_DE_THRESHOLD, higher_is_better=False)')
L('        de_str = f"{de:.2f}"')
L('        return {"rule_id": "CON_01", "text": f"Debt-to-equity ratio of {de_str} is elevated for a non-financial company and warrants monitoring", "confidence_pct": confidence}')
L('    return None')
L('')
L('')
L('def _con_02_fcf_negative_3yr(data):')
L('    """CON_02: FCF negative for 3 consecutive years."""')
L('    fcf_values = _extract_annual_trend(data["annual_kpis"], "free_cash_flow", CON_02_FCF_YEARS)')
L('    valid_fcf = [v for v in fcf_values if v is not None]')
L('    if len(valid_fcf) < CON_02_FCF_YEARS:')
L('        cf_values = _extract_annual_trend(data["cash_flow"], "free_cash_flow", CON_02_FCF_YEARS)')
L('        valid_fcf = [v for v in cf_values if v is not None]')
L('    if len(valid_fcf) < CON_02_FCF_YEARS:')
L('        return None')
L('    if all(v < 0 for v in valid_fcf):')
L('        confidence = calculate_confidence(valid_fcf[0], 0, higher_is_better=False)')
L('        return {"rule_id": "CON_02", "text": "Free cash flow negative for 3 consecutive years raises concern about cash generation quality", "confidence_pct": confidence}')
L('    return None')
L('')
L('')
L('def _con_03_opm_declining_3yr(data):')
L('    """CON_03: OPM declining for 3 consecutive years."""')
L('    opm_values = _extract_annual_trend(data["annual_kpis"], "operating_margin", CON_03_OPM_DECLINE_YEARS)')
L('    valid_opm = [v for v in opm_values if v is not None]')
L('    if len(valid_opm) < CON_03_OPM_DECLINE_YEARS:')
L('        opm_values_pl = _extract_annual_trend(data["annual_pl"], "opm_percentage", CON_03_OPM_DECLINE_YEARS)')
L('        valid_opm = [v for v in opm_values_pl if v is not None]')
L('    if len(valid_opm) < CON_03_OPM_DECLINE_YEARS:')
L('        return None')
L('    declining = all(valid_opm[i] < valid_opm[i + 1] for i in range(len(valid_opm) - 1))')
L('    if declining:')
L('        confidence = calculate_trend_confidence(valid_opm, improving=False)')
L('        return {"rule_id": "CON_03", "text": "Operating margins declining for 3 consecutive years suggest pricing or cost pressure", "confidence_pct": confidence}')
L('    return None')
L('')
L('')
L('def _con_04_net_loss_latest(data):')
L('    """CON_04: Latest-year net profit < 0."""')
L('    net_profit = _get_numeric(data["annual_pl"], "net_profit", 0)')
L('    if net_profit is not None and net_profit < 0:')
L('        confidence = calculate_confidence(net_profit, 0, higher_is_better=False)')
L('        return {"rule_id": "CON_04", "text": "Company reported a net loss in the most recent financial year", "confidence_pct": confidence}')
L('    return None')
L('')
L('')
L('def _con_05_revenue_declining_2yr(data):')
L('    """CON_05: Revenue declining for 2+ years."""')
L('    revenue_values = _extract_annual_trend(data["annual_pl"], "sales", CON_05_REVENUE_DECLINE_YEARS + 1)')
L('    valid = [v for v in revenue_values if v is not None]')
L('    if len(valid) < CON_05_REVENUE_DECLINE_YEARS + 1:')
L('        return None')
L('    declining = all(valid[i] < valid[i + 1] for i in range(CON_05_REVENUE_DECLINE_YEARS))')
L('    if declining:')
L('        confidence = calculate_trend_confidence(valid[: CON_05_REVENUE_DECLINE_YEARS + 1], improving=False)')
L('        return {"rule_id": "CON_05", "text": "Revenue contraction over 2 consecutive years indicates demand weakness or market share loss", "confidence_pct": confidence}')
L('    return None')
L('')
L('')
L('def _con_06_icr_low(data):')
L('    """CON_06: ICR < 1.5."""')
L('    icr = _get_numeric(data["annual_kpis"], "interest_coverage", 0)')
L('    if icr is None:')
L('        return None')
L('    if icr < CON_06_ICR_THRESHOLD:')
L('        confidence = calculate_confidence(icr, CON_06_ICR_THRESHOLD, higher_is_better=False)')
L('        return {"rule_id": "CON_06", "text": "Interest coverage ratio below 1.5x indicates the company is at risk of not meeting its debt obligations", "confidence_pct": confidence}')
L('    return None')
L('')

L('')
